# config/packages/fos_user.yaml
fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address:        noreply@example.com
    sender_name:    Регистрация ProjectTest
  registration:
    confirmation:
      enabled: true
    form:
      type: App\Form\RegistrationType

